spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 971806293101-iip48f18err1i9i52biiti128jgmb33h.apps.googleusercontent.com
            client-secret: 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
