spring:
  datasource:
    password: 201712455@Asg
    url: jdbc:mysql://localhost:3306/app_schema
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show_sql: true

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 9090

